### PR TITLE
added conditional on sessions signup page so if no mentors are availa…

### PR DESCRIPTION
**Pull request by capelhoworth**
…ble at a selected time then a message displays telling the user

### **1. Targeted Issue** ###

Render a message to show that the skills/time frame selected does not have any mentors available

Ticket #114

### **2. Overview of Solution** ###

Put a conditional (filteredMentors.length === 0 ?) that would display "No Mentors are available at this time." when array length was zero.

### **3. Tools Used** ###

React and MUI

### **4. Testing Strategy** ###

Usage

### **5. Future Implications** ###

Users will immediately know that their search parameters do not yield a search result instead of a malfunction occurring in the app.

### **6. Screenshots** ###

Screenshot 2023-09-01 at 10 30 22 AM

Screenshot 2023-09-01 at 10 31 02 AM

### **7. Code Reviewers** ###

Luke or Nathan will do the PR?

---

Before you go...

- [x]  I have linked the relevant issue
- [x]  I have provided an overview of my solution
- [x]  I have shared the tools I've used
- [x]  I have outlined my testing strategy
- [x]  I have considered future implications of my changes
- [x]  I have included relevant screenshots
- [x]  I have kept my team in the loop

---

### CODE REVIEW

**Review by nzeager — CHANGES_REQUESTED** [review]
This is a great update! Even though this ended up being something different than the origin ticket, I think it will help a lot. And thanks for cleaning up the code some while you were at it. A few changes before I approve:
1) Update the ticket number in the PR description from 60 to 114, to match the new trello ticket I created.
2) Can you update the displayed message to say “No mentors are available for <insert topic> on this day.”? I want it to convey that there may be mentors available for that skill on other days, or mentors helping with other skills on the selected day. Feel free to suggest other ideas.
3) The message currently displays when they haven’t selected a topic or day. Can we hide it in that case?
4) Indent the message further in than the text “Select a mentor for:”.

I've added a screenshot for reference of fixes 2-4.
Screen Shot 2023-09-01 at 4 40 42 PM

**Comment by capelhoworth** [comment]
Screenshot 2023-09-05 at 6 43 43 PM

**Review by nzeager — CHANGES_REQUESTED** [review]
Updates look great!

**Edit**: meant to approve rather than request changes

**Review by nzeager — APPROVED** [review]
Updates look great!

**Pull request merged**
